apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- psql.secret.yaml
- db.spec.yaml
- storage.yaml
- network.yaml
images:
- name: ghcr.io/mealie-recipes/mealie
  newTag: v3.9.2
